/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Correlation,
    CorrelationFromJSON,
    CorrelationToJSON,
    GetCorrelationsResponse,
    GetCorrelationsResponseFromJSON,
    GetCorrelationsResponseToJSON,
} from '../models';

export interface GetCorrelationExplanationsRequest {
    causeVariableName?: string;
    effectVariableName?: string;
    causeVariableId?: number;
    effectVariableId?: number;
    predictorVariableName?: string;
    outcomeVariableName?: string;
}

export interface GetCorrelationsRequest {
    causeVariableName?: string;
    effectVariableName?: string;
    causeVariableId?: number;
    effectVariableId?: number;
    predictorVariableName?: string;
    outcomeVariableName?: string;
    sort?: string;
    limit?: number;
    offset?: number;
    userId?: number;
    correlationCoefficient?: string;
    updatedAt?: string;
    outcomesOfInterest?: boolean;
    clientId?: string;
    commonOnly?: boolean;
    platform?: GetCorrelationsPlatformEnum;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Get explanations of  correlations based on data from a single user.
     * Get correlation explanations
     */
    async getCorrelationExplanationsRaw(requestParameters: GetCorrelationExplanationsRequest): Promise<runtime.ApiResponse<Array<Correlation>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.causeVariableName !== undefined) {
            queryParameters['causeVariableName'] = requestParameters.causeVariableName;
        }

        if (requestParameters.effectVariableName !== undefined) {
            queryParameters['effectVariableName'] = requestParameters.effectVariableName;
        }

        if (requestParameters.causeVariableId !== undefined) {
            queryParameters['causeVariableId'] = requestParameters.causeVariableId;
        }

        if (requestParameters.effectVariableId !== undefined) {
            queryParameters['effectVariableId'] = requestParameters.effectVariableId;
        }

        if (requestParameters.predictorVariableName !== undefined) {
            queryParameters['predictorVariableName'] = requestParameters.predictorVariableName;
        }

        if (requestParameters.outcomeVariableName !== undefined) {
            queryParameters['outcomeVariableName'] = requestParameters.outcomeVariableName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // access_token authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("quantimodo_oauth2", ["basic"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/v3/correlations/explanations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CorrelationFromJSON));
    }

    /**
     * Get explanations of  correlations based on data from a single user.
     * Get correlation explanations
     */
    async getCorrelationExplanations(requestParameters: GetCorrelationExplanationsRequest): Promise<Array<Correlation>> {
        const response = await this.getCorrelationExplanationsRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get a list of correlations that can be used to display top predictors of a given outcome like mood, for instance.
     * Get correlations
     */
    async getCorrelationsRaw(requestParameters: GetCorrelationsRequest): Promise<runtime.ApiResponse<GetCorrelationsResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.causeVariableName !== undefined) {
            queryParameters['causeVariableName'] = requestParameters.causeVariableName;
        }

        if (requestParameters.effectVariableName !== undefined) {
            queryParameters['effectVariableName'] = requestParameters.effectVariableName;
        }

        if (requestParameters.causeVariableId !== undefined) {
            queryParameters['causeVariableId'] = requestParameters.causeVariableId;
        }

        if (requestParameters.effectVariableId !== undefined) {
            queryParameters['effectVariableId'] = requestParameters.effectVariableId;
        }

        if (requestParameters.predictorVariableName !== undefined) {
            queryParameters['predictorVariableName'] = requestParameters.predictorVariableName;
        }

        if (requestParameters.outcomeVariableName !== undefined) {
            queryParameters['outcomeVariableName'] = requestParameters.outcomeVariableName;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters['offset'] = requestParameters.offset;
        }

        if (requestParameters.userId !== undefined) {
            queryParameters['userId'] = requestParameters.userId;
        }

        if (requestParameters.correlationCoefficient !== undefined) {
            queryParameters['correlationCoefficient'] = requestParameters.correlationCoefficient;
        }

        if (requestParameters.updatedAt !== undefined) {
            queryParameters['updatedAt'] = requestParameters.updatedAt;
        }

        if (requestParameters.outcomesOfInterest !== undefined) {
            queryParameters['outcomesOfInterest'] = requestParameters.outcomesOfInterest;
        }

        if (requestParameters.clientId !== undefined) {
            queryParameters['clientId'] = requestParameters.clientId;
        }

        if (requestParameters.commonOnly !== undefined) {
            queryParameters['commonOnly'] = requestParameters.commonOnly;
        }

        if (requestParameters.platform !== undefined) {
            queryParameters['platform'] = requestParameters.platform;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["access_token"] = this.configuration.apiKey("access_token"); // access_token authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("quantimodo_oauth2", ["basic"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/v3/correlations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCorrelationsResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of correlations that can be used to display top predictors of a given outcome like mood, for instance.
     * Get correlations
     */
    async getCorrelations(requestParameters: GetCorrelationsRequest): Promise<GetCorrelationsResponse> {
        const response = await this.getCorrelationsRaw(requestParameters);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetCorrelationsPlatformEnum {
    Chrome = 'chrome',
    Android = 'android',
    Ios = 'ios',
    Web = 'web'
}
