/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PostUploadResponse,
    PostUploadResponseFromJSON,
    PostUploadResponseToJSON,
} from '../models';

export interface V2UploadPostRequest {
    upfile?: Blob;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Uploads a file.
     */
    async v2UploadPostRaw(requestParameters: V2UploadPostRequest): Promise<runtime.ApiResponse<PostUploadResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.upfile !== undefined) {
            formParams.append('upfile', requestParameters.upfile as any);
        }

        const response = await this.request({
            path: `/v2/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PostUploadResponseFromJSON(jsonValue));
    }

    /**
     * Uploads a file.
     */
    async v2UploadPost(requestParameters: V2UploadPostRequest): Promise<PostUploadResponse> {
        const response = await this.v2UploadPostRaw(requestParameters);
        return await response.value();
    }

}
