/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessagesMessage
 */
export interface MessagesMessage {
    /**
     * What do you expect?
     * @type {number}
     * @memberof MessagesMessage
     */
    id: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof MessagesMessage
     */
    threadId: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof MessagesMessage
     */
    senderId: number;
    /**
     * What do you expect?
     * @type {string}
     * @memberof MessagesMessage
     */
    subject: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof MessagesMessage
     */
    message: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof MessagesMessage
     */
    dateSent: string;
    /**
     * Additional messagesmessage key-value data
     * @type {Array<object>}
     * @memberof MessagesMessage
     */
    metaDataArray?: Array<object>;
}

export function MessagesMessageFromJSON(json: any): MessagesMessage {
    return MessagesMessageFromJSONTyped(json, false);
}

export function MessagesMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagesMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'threadId': json['threadId'],
        'senderId': json['senderId'],
        'subject': json['subject'],
        'message': json['message'],
        'dateSent': json['dateSent'],
        'metaDataArray': !exists(json, 'metaDataArray') ? undefined : json['metaDataArray'],
    };
}

export function MessagesMessageToJSON(value?: MessagesMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'threadId': value.threadId,
        'senderId': value.senderId,
        'subject': value.subject,
        'message': value.message,
        'dateSent': value.dateSent,
        'metaDataArray': value.metaDataArray,
    };
}


