/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * What do you expect?
     * @type {number}
     * @memberof Notification
     */
    id: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof Notification
     */
    userId: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof Notification
     */
    itemId: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof Notification
     */
    secondaryItemId: number;
    /**
     * What do you expect?
     * @type {string}
     * @memberof Notification
     */
    componentName: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof Notification
     */
    componentAction: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof Notification
     */
    dateNotified: string;
    /**
     * What do you expect?
     * @type {number}
     * @memberof Notification
     */
    isNew: number;
    /**
     * Additional notification key-value data
     * @type {Array<object>}
     * @memberof Notification
     */
    metaDataArray?: Array<object>;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'itemId': json['itemId'],
        'secondaryItemId': json['secondaryItemId'],
        'componentName': json['componentName'],
        'componentAction': json['componentAction'],
        'dateNotified': json['dateNotified'],
        'isNew': json['isNew'],
        'metaDataArray': !exists(json, 'metaDataArray') ? undefined : json['metaDataArray'],
    };
}

export function NotificationToJSON(value?: Notification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'itemId': value.itemId,
        'secondaryItemId': value.secondaryItemId,
        'componentName': value.componentName,
        'componentAction': value.componentAction,
        'dateNotified': value.dateNotified,
        'isNew': value.isNew,
        'metaDataArray': value.metaDataArray,
    };
}


