/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Chart,
    ChartFromJSON,
    ChartFromJSONTyped,
    ChartToJSON,
} from './';

/**
 * An object with various chart properties each property contain and svg and Highcharts configuration
 * @export
 * @interface VariableCharts
 */
export interface VariableCharts {
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    hourlyColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    monthlyColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    distributionColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    weekdayColumnChart?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    lineChartWithoutSmoothing?: Chart;
    /**
     * 
     * @type {Chart}
     * @memberof VariableCharts
     */
    lineChartWithSmoothing?: Chart;
}

export function VariableChartsFromJSON(json: any): VariableCharts {
    return VariableChartsFromJSONTyped(json, false);
}

export function VariableChartsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableCharts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hourlyColumnChart': !exists(json, 'hourlyColumnChart') ? undefined : ChartFromJSON(json['hourlyColumnChart']),
        'monthlyColumnChart': !exists(json, 'monthlyColumnChart') ? undefined : ChartFromJSON(json['monthlyColumnChart']),
        'distributionColumnChart': !exists(json, 'distributionColumnChart') ? undefined : ChartFromJSON(json['distributionColumnChart']),
        'weekdayColumnChart': !exists(json, 'weekdayColumnChart') ? undefined : ChartFromJSON(json['weekdayColumnChart']),
        'lineChartWithoutSmoothing': !exists(json, 'lineChartWithoutSmoothing') ? undefined : ChartFromJSON(json['lineChartWithoutSmoothing']),
        'lineChartWithSmoothing': !exists(json, 'lineChartWithSmoothing') ? undefined : ChartFromJSON(json['lineChartWithSmoothing']),
    };
}

export function VariableChartsToJSON(value?: VariableCharts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hourlyColumnChart': ChartToJSON(value.hourlyColumnChart),
        'monthlyColumnChart': ChartToJSON(value.monthlyColumnChart),
        'distributionColumnChart': ChartToJSON(value.distributionColumnChart),
        'weekdayColumnChart': ChartToJSON(value.weekdayColumnChart),
        'lineChartWithoutSmoothing': ChartToJSON(value.lineChartWithoutSmoothing),
        'lineChartWithSmoothing': ChartToJSON(value.lineChartWithSmoothing),
    };
}


