/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XprofileGroup
 */
export interface XprofileGroup {
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileGroup
     */
    id: number;
    /**
     * What do you expect?
     * @type {string}
     * @memberof XprofileGroup
     */
    name: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof XprofileGroup
     */
    description: string;
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileGroup
     */
    groupOrder: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileGroup
     */
    canDelete: number;
    /**
     * Additional xprofilegroup key-value data
     * @type {Array<object>}
     * @memberof XprofileGroup
     */
    metaDataArray?: Array<object>;
}

export function XprofileGroupFromJSON(json: any): XprofileGroup {
    return XprofileGroupFromJSONTyped(json, false);
}

export function XprofileGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): XprofileGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'groupOrder': json['groupOrder'],
        'canDelete': json['canDelete'],
        'metaDataArray': !exists(json, 'metaDataArray') ? undefined : json['metaDataArray'],
    };
}

export function XprofileGroupToJSON(value?: XprofileGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'groupOrder': value.groupOrder,
        'canDelete': value.canDelete,
        'metaDataArray': value.metaDataArray,
    };
}


