/* tslint:disable */
/* eslint-disable */
/**
 * quantimodo
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk\'s](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * The version of the OpenAPI document: 5.8.112511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XprofileDatum
 */
export interface XprofileDatum {
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileDatum
     */
    id: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileDatum
     */
    fieldId: number;
    /**
     * What do you expect?
     * @type {number}
     * @memberof XprofileDatum
     */
    userId: number;
    /**
     * What do you expect?
     * @type {string}
     * @memberof XprofileDatum
     */
    value: string;
    /**
     * What do you expect?
     * @type {string}
     * @memberof XprofileDatum
     */
    lastUpdated: string;
    /**
     * Additional xprofiledatum key-value data
     * @type {Array<object>}
     * @memberof XprofileDatum
     */
    metaDataArray?: Array<object>;
}

export function XprofileDatumFromJSON(json: any): XprofileDatum {
    return XprofileDatumFromJSONTyped(json, false);
}

export function XprofileDatumFromJSONTyped(json: any, ignoreDiscriminator: boolean): XprofileDatum {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fieldId': json['fieldId'],
        'userId': json['userId'],
        'value': json['value'],
        'lastUpdated': json['lastUpdated'],
        'metaDataArray': !exists(json, 'metaDataArray') ? undefined : json['metaDataArray'],
    };
}

export function XprofileDatumToJSON(value?: XprofileDatum | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fieldId': value.fieldId,
        'userId': value.userId,
        'value': value.value,
        'lastUpdated': value.lastUpdated,
        'metaDataArray': value.metaDataArray,
    };
}


